### ISSUE TITLE
binned_statistic issue

### ISSUE THREAD

**Issue by chrisvam** [scikit-beam/scikit-beam#503]
Hi guys,

We have this version installed:

pslogin7d:cpo$ conda list | grep beam
scikit-beam               0.0.10              np111py27_0    conda-forge
pslogin7d:cpo$

However, that version seems to have an infinite recursion bug in it that has been fixed in the HEAD.  Broken version:

    @property
    def statistic(self):
        return self.statistic

The fix in the HEAD changes the return to self._statistic.  Would you be able to put a version with the fix into conda-forge?  Or am I picking up a wrong/old version somehow?

Thanks...

chris

**Comment by licode** [comment]
Can you send a PR to fix this? I will add a new version number for conda-forge.

**Comment by chrisvam** [comment]
Hi Li,

Since it's already fixed in the HEAD, can you tell me what my PR should contain?  Apologies if I'm being slow...

chris

**Comment by licode** [comment]
OK. I thought it was not fixed yet in the current master branch. I will go ahead to put a new version.

**Comment by chrisvam** [comment]
Thanks Li!

**Comment by danielballan** [comment]
Yep, fixed in master many months ago but no one found time to tag and ship a release with the fix. We also fixed Travis-CI so that this shouldn't happen again.

**Comment by licode** [comment]
Please update scikit-beam to version 0.0.12 from conda-forge, and try it again.
